(function(root){
 'use strict';const names=['shoulder-left','shoulder-right','core','right-hand','left-hand','left-upper-arm','left-forearm','sword'],images={},cache=new Map(),frames=new WeakMap();let ready=false,error=false,promise;
 // Provisional common camera. D and pitch await the supervisor's full-scene review.
 const camera={coreDiameter:12,pixelPitch:2,status:'provisional-awaiting-full-scene-acceptance'},S=camera.coreDiameter/28,anchor={x:268,y:215},rig={shoulder:{x:184,y:204},elbow:{x:135,y:225},wrist:{x:112,y:261},grip:{x:120,y:275},bladeTip:{x:504,y:385}};
 const rotate=(p,a)=>({x:p.x*Math.cos(a)-p.y*Math.sin(a),y:p.x*Math.sin(a)+p.y*Math.cos(a)}),lerp=(a,b,k)=>a+(b-a)*k,clamp=x=>Math.max(0,Math.min(1,x));
 function load(){if(ready)return Promise.resolve();if(promise)return promise;error=false;promise=Promise.all(names.map(n=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve([n,im]);im.onerror=()=>reject(Error('approved-v6-part-load-failed'));im.src='assets/warrior-p0/'+n+'.png';}))).then(pair=>{Object.assign(images,Object.fromEntries(pair));ready=true;}).catch(e=>{error=true;throw e;}).finally(()=>promise=null);return promise;}
 function core(look){const key=JSON.stringify([look.tone,look.hue,look.eyeColor,look.eyes,look.mouth]);if(cache.has(key))return cache.get(key);const b=document.createElement('canvas');b.width=b.height=512;const c=b.getContext('2d');c.drawImage(images.core,0,0);const data=c.getImageData(0,0,512,512),d=data.data,hue=(Number.isFinite(look.hue)?look.hue:270)-270;
  for(let y=0;y<512;y++)for(let x=0;x<512;x++){const i=(y*512+x)*4;if(!d[i+3])continue;const eye=x>=260&&x<=277&&y>=210&&y<=220&&d[i]>180&&d[i+1]>135&&d[i+2]>190;if(eye){const nearby=(y*512+Math.max(250,x-10))*4;for(let n=0;n<3;n++)d[i+n]=d[nearby+n];}if(look.tone==='white'){const l=(d[i]+d[i+1]+d[i+2])/3;d[i]=150+l*.4;d[i+1]=158+l*.4;d[i+2]=172+l*.35;}else if(hue||look.tone==='pastel'||look.tone==='vivid'){const rr=d[i]/255,gg=d[i+1]/255,bb=d[i+2]/255,max=Math.max(rr,gg,bb),min=Math.min(rr,gg,bb),dif=max-min;let h=dif?max===rr?((gg-bb)/dif)%6:max===gg?(bb-rr)/dif+2:(rr-gg)/dif+4:0;h=((h*60+hue)%360+360)%360;const l=(max+min)/2,s=dif?dif/(1-Math.abs(2*l-1)):0,ll=look.tone==='pastel'?.65+l*.25:look.tone==='vivid'?.3+l*.5:l,ss=look.tone==='pastel'?s*.45:s,cc=(1-Math.abs(2*ll-1))*ss,xx=cc*(1-Math.abs(h/60%2-1)),m=ll-cc/2,rgb=h<60?[cc,xx,0]:h<120?[xx,cc,0]:h<180?[0,cc,xx]:h<240?[0,xx,cc]:h<300?[xx,0,cc]:[cc,0,xx];for(let n=0;n<3;n++)d[i+n]=(rgb[n]+m)*255;}}
  c.putImageData(data,0,0);if(cache.size>16)cache.delete(cache.keys().next().value);cache.set(key,b);return b;
 }
 function pose(look,action,target,center,reduced){const baseGrip={x:rig.grip.x-anchor.x,y:rig.grip.y-anchor.y},shoulder={x:rig.shoulder.x-anchor.x,y:rig.shoulder.y-anchor.y};let arm=0,blade=-1.05;
  const elbowAngle=a=>a*.45,point=(raw,a)=>{const e=rotate({x:rig.elbow.x-rig.shoulder.x,y:rig.elbow.y-rig.shoulder.y},a),p=rotate({x:raw.x-rig.elbow.x,y:raw.y-rig.elbow.y},a+elbowAngle(a));return {x:center.x+(shoulder.x+e.x+p.x)*S,y:center.y+(shoulder.y+e.y+p.y)*S};};const contactAngle=a=>{const w=point(rig.wrist,a);return Math.atan2(target.y-w.y,target.x-w.x)-Math.atan2(rig.bladeTip.y-rig.wrist.y,rig.bladeTip.x-rig.wrist.x);};
  if(action&&action.kind!=='impact'&&(action.style||look.weapon)==='sword'&&!reduced){const wind=clamp(action.elapsed/Math.max(.01,action.windup));if(action.stage==='windup'){if(wind<.60){const k=wind/.60;arm=-.40*k;blade=lerp(-1.05,-1.58,k);}else{const k=(wind-.60)/.40;arm=lerp(-.40,.30,k);blade=lerp(-1.58,contactAngle(.30),k);}}else if(action.stage==='contact'){arm=.30;blade=contactAngle(arm);}else if(action.hitIndex<action.hitCount){const since=action.elapsed-action.windup-(Math.max(1,action.hitIndex)-1)*action.beat-action.hitstop,gap=action.beat-action.hitstop,k=clamp(since/gap);if(k<.55){arm=lerp(.30,-.40,k/.55);blade=lerp(contactAngle(.30),-1.58,k/.55);}else{arm=lerp(-.40,.30,(k-.55)/.45);blade=lerp(-1.58,contactAngle(.30),(k-.55)/.45);}}else{const k=clamp(action.contactAge/.32);arm=lerp(.30,0,k);blade=lerp(contactAngle(.30),-1.05,k);}}
  const wrist=point(rig.wrist,arm),weapon=action?.style||look.weapon||'sword';let handAngle=weapon==='sword'?blade:arm+elbowAngle(arm),grip;const locate=()=>{const v=rotate({x:(rig.grip.x-rig.wrist.x)*S,y:(rig.grip.y-rig.wrist.y)*S},handAngle);grip={x:wrist.x+v.x,y:wrist.y+v.y};};locate();if(['machinegun','thunder'].includes(weapon)&&target!==center){for(let i=0;i<3;i++){handAngle=Math.atan2(target.y-grip.y,target.x-grip.x)-Math.atan2(110,384);locate();}}const tip=rotate({x:(rig.bladeTip.x-rig.grip.x)*S,y:(rig.bladeTip.y-rig.grip.y)*S},blade),e=rotate({x:rig.elbow.x-rig.shoulder.x,y:rig.elbow.y-rig.shoulder.y},arm),shoulderWorld={x:center.x+shoulder.x*S,y:center.y+shoulder.y*S},elbowWorld={x:center.x+(shoulder.x+e.x)*S,y:center.y+(shoulder.y+e.y)*S};return {arm,elbowAngle:elbowAngle(arm),forearmAngle:arm+elbowAngle(arm),handAngle,wristAngle:handAngle-arm-elbowAngle(arm),blade,grip,bladeTip:weapon==='sword'?{x:grip.x+tip.x,y:grip.y+tip.y}:null,shoulder:shoulderWorld,upperArm:{from:shoulderWorld,to:elbowWorld,angle:arm},forearm:{from:elbowWorld,to:wrist,angle:arm+elbowAngle(arm)},elbow:elbowWorld,wrist};
 }
 function drawAt(c,look,center,{time=0,reduced=false,action=null,target=center,walk=0}={}){if(!ready)return null;const parts=look.parts||[],p=pose(look,action,target,center,reduced),weapon=action?.style||look.weapon||'sword';
  function layer(n,pos=center,pivot=anchor,angle=0){c.save();c.translate(pos.x,pos.y);c.rotate(angle);c.imageSmoothingEnabled=false;c.globalAlpha=(look.lockedParts||[]).includes(n.startsWith('shoulder')?'armor':'arms')?.28:1;c.drawImage(images[n],-pivot.x*S,-pivot.y*S,512*S,512*S);c.restore();}
  if(parts.includes('armor')){layer('shoulder-left');layer('shoulder-right');}if(parts.includes('arms')){layer('right-hand');layer('left-upper-arm',p.shoulder,rig.shoulder,p.arm);layer('left-forearm',p.elbow,rig.elbow,p.forearmAngle);}
  // The approved gripping fist supports the chosen weapon, independently of owned giant arms.
  if(weapon!=='none'){if(weapon==='sword')layer('sword',p.grip,rig.grip,p.blade);else{c.save();c.translate(p.grip.x,p.grip.y);const angle=target===center?0:Math.atan2(target.y-p.grip.y,target.x-p.grip.x);c.rotate(angle);c.fillStyle='#26334e';c.fillRect(-3,-3,weapon==='machinegun'?30:5,6);c.fillStyle=weapon==='machinegun'?'#a3abbc':'#aeecff';c.fillRect(4,-2,weapon==='machinegun'?26:5,2);if(weapon==='thunder'){c.fillRect(5,-12,2,20);}c.restore();}layer('left-hand',p.wrist,rig.wrist,p.handAngle);}
  c.save();c.translate(Math.round(center.x),Math.round(center.y));c.drawImage(core(look),-anchor.x*S,-anchor.y*S,512*S,512*S);const col=/^#[0-9a-f]{6}$/i.test(look.eyeColor||'')?look.eyeColor:'#ffffff';c.fillStyle=col;for(const side of [-1,1]){const x=side*2;if(look.eyes==='line')c.fillRect(x-1,-1,2,1);else if(look.eyes==='arc'){c.fillRect(x-1,-2,2,1);c.fillRect(x-2,-1,1,1);}else if(look.eyes==='oval')c.fillRect(x-1,-2,2,2);else c.fillRect(x-1,-3,2,4);}c.fillStyle=look.tone==='white'?'#514963':'#251539';if(look.mouth==='flat')c.fillRect(-1,3,3,1);else if(look.mouth==='dot')c.fillRect(0,3,1,1);else if(look.mouth==='smile'){c.fillRect(-2,2,1,1);c.fillRect(-1,3,3,1);c.fillRect(2,2,1,1);}else if(['teeth','fang'].includes(look.mouth)){c.fillRect(-2,2,5,2);c.fillStyle=col;c.fillRect(-1,2,1,look.mouth==='fang'?2:1);c.fillRect(1,2,1,look.mouth==='fang'?2:1);}c.restore();return {...p,weapon,coreDiameter:camera.coreDiameter};
 }
 let extrasDraw;
 function setExtras(draw){extrasDraw=draw;}
 function extras(c,look,center,time,reduced,walk=0){const parts=(look.parts||[]).filter(p=>!['armor','arms'].includes(p));if(!extrasDraw||(!parts.length&&look.locomotion!=='legs'))return;const im=document.createElement('canvas');im.width=100;im.height=100;extrasDraw(im,{...look,parts,weapon:'none'},time,reduced,{walk});const cc=im.getContext('2d');cc.globalCompositeOperation='destination-out';cc.fillStyle='#000';cc.beginPath();cc.ellipse(50,52,12,12,0,0,Math.PI*2);cc.fill();c.drawImage(im,center.x-50*camera.coreDiameter/23,center.y-52*camera.coreDiameter/23,100*camera.coreDiameter/23,100*camera.coreDiameter/23);}
 function draw(canvas,look,time=0,reduced=false,options={}){if(!ready){load().catch(()=>{});return false;}const rect=canvas.getBoundingClientRect(),css=rect.width||canvas.width,lw=Math.max(1,Math.round(css/camera.pixelPitch)),lh=Math.max(1,Math.round((rect.height||canvas.height)/camera.pixelPitch));let f=frames.get(canvas);if(!f){f=document.createElement('canvas');frames.set(canvas,f);}f.width=lw;f.height=lh;const c=f.getContext('2d');c.imageSmoothingEnabled=false;const center={x:lw/2,y:lh-40};extras(c,look,center,time,reduced,options.walk);drawAt(c,look,center,{time,reduced,...options});const out=canvas.getContext('2d');out.clearRect(0,0,canvas.width,canvas.height);out.imageSmoothingEnabled=false;out.drawImage(f,0,0,canvas.width,canvas.height);canvas.dataset.material='approved-v6-common-camera-provisional';canvas.dataset.coreDiameter=String(camera.coreDiameter);canvas.dataset.pixelPitch=String(camera.pixelPitch);return true;}
 root.AwaiAppearance={load,draw,drawAt,extras,setExtras,pose,camera,rig,inspect:()=>({ready,error,camera,rig,sourceSha256:'9ce33960105908055f1a02d4bf9cc34ac234bad6c24b9d5eaf4dffa1260590a3',hiddenSurfaces:'no newly painted surfaces; aesthetic review pending'})};
 root.AwaiWarriorMaterial={load,draw,uses:()=>true,inspect:root.AwaiAppearance.inspect};
})(globalThis);

