(function(){
  'use strict';const E=AwaiEngine,C=AwaiCombat,P=AwaiEquipmentPreview,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),trial=params.get('trial')==='1',slot=trial&&/^[a-z0-9-]{8,48}$/.test(params.get('slot')||'')?params.get('slot'):null,suffix=trial?(slot?'.trial.'+slot:'.trial'):'';
  const source=E.load({getItem:k=>localStorage.getItem(k+suffix)}).state;C.ensure(source);let preview=AwaiFittingDraft.decode(location.hash)||P.create(source);
  const back=new URL('index.html',location.href);back.searchParams.set('view','custom');if(trial){back.searchParams.set('trial','1');if(slot)back.searchParams.set('slot',slot);}$('preview-back').href=back.href;
  const canvas=$('preview-avatar'),motion=matchMedia('(prefers-reduced-motion: reduce)');
  for(const [id,part] of Object.entries(C.PARTS)){const b=document.createElement('button');b.textContent=part.name;b.dataset.previewPart=id;b.title=source.gameplay.parts.includes(id)?'所有済み · 自由に試着':'未所有・未解放でも試着できます';b.addEventListener('click',()=>{P.toggle(preview,id);render();});$('preview-parts').append(b);}
  function render(){history.replaceState(null,'',location.pathname+location.search+'#'+AwaiFittingDraft.encode(preview));$('preview-fight').href=AwaiFittingDraft.url('realtime.html',preview,'fitting=1'+(trial?'&trial=1'+(slot?'&slot='+slot:''):''));for(const [attr,selected] of [['part',preview.parts],['weapon',[preview.weapon]],['move',[preview.locomotion]],['tone',[preview.appearance.tone]],['eye',[preview.appearance.eyeColor]],['eyes',[preview.appearance.eyes]],['mouth',[preview.appearance.mouth]]])document.querySelectorAll('[data-preview-'+attr+']').forEach(b=>b.setAttribute('aria-pressed',String(selected.includes(b.getAttribute('data-preview-'+attr)))));$('preview-hue').value=preview.appearance.hue;$('preview-description').textContent=(preview.parts.length?preview.parts.map(id=>C.PARTS[id].name).join(' / '):'丸い核')+' · '+({sword:'大剣',machinegun:'銃',thunder:'雷',none:'武器なし'}[preview.weapon]);AwaiCreature.draw(canvas,P.look(preview),0,true);}
  document.querySelectorAll('[data-preview-preset]').forEach(b=>b.addEventListener('click',()=>{P.preset(preview,b.dataset.previewPreset);render();}));
  for(const [attr,key] of [['weapon','weapon'],['move','locomotion']])document.querySelectorAll('[data-preview-'+attr+']').forEach(b=>b.addEventListener('click',()=>{preview[key]=b.getAttribute('data-preview-'+attr);render();}));
  for(const [attr,key] of [['tone','tone'],['eye','eyeColor'],['eyes','eyes'],['mouth','mouth']])document.querySelectorAll('[data-preview-'+attr+']').forEach(b=>b.addEventListener('click',()=>{preview.appearance[key]=b.getAttribute('data-preview-'+attr);render();}));
  $('preview-hue').addEventListener('input',e=>{preview.appearance.hue=Number(e.target.value);render();});$('preview-original').addEventListener('click',()=>{preview=P.create(source);render();});
  let last=0;function frame(now){if(!document.hidden&&now-last>=80){last=now;AwaiCreature.draw(canvas,P.look(preview),now,motion.matches);}requestAnimationFrame(frame);}render();requestAnimationFrame(frame);
  window.AwaiPreview={current:()=>P.look(preview),sourceId:source.id};
})();
