(function(){
  'use strict';const E=AwaiEngine,C=AwaiCombat,R=AwaiRealtime,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),capture=document.body.dataset.capture==='1',trial=params.get('trial')==='1',slot=trial&&/^[a-z0-9-]{8,48}$/.test(params.get('slot')||'')?params.get('slot'):null,suffix=trial?(slot?'.trial.'+slot:'.trial'):'',KEY='awai.scene.realtime.v1'+suffix+(capture?'.capture':'');
  const loaded=E.load({getItem:k=>localStorage.getItem(k+suffix)});let saved,source=loaded.state;try{saved=JSON.parse(localStorage.getItem(KEY));if(!loaded.restored&&saved?.sourceSnapshot&&typeof saved.sourceSnapshot.id==='string')source=E.hydrate(saved.sourceSnapshot);}catch{}C.ensure(source);const stats=C.effective(source.gameplay),look={...source.appearance,parts:[...source.gameplay.equipped],locomotion:source.gameplay.locomotion},signature=source.id+JSON.stringify(stats)+JSON.stringify(look.parts);let state=saved?.signature===signature?R.hydrate(saved.battle):null;if(!state)state=R.create(stats);
  const back=new URL('index.html',location.href);if(trial){back.searchParams.set('trial','1');if(slot)back.searchParams.set('slot',slot);}if(!capture)$('rt-back').href=back.href;
  if(!loaded.restored&&!capture)$('rt-source-note').textContent='育成の保存がないため、この一戦だけの相棒です。相棒と戦闘をこの端末に保存し、元の育成枠は変更しません。経験・報酬は増えません。画面を離れると一時停止します。';
  const D=AwaiRealtimeDirector,sprites={},assetUrls={player:capture?AwaiCaptureActor.imageUrl():'assets/amethyst_regent_sprite_192.png',enemy:'assets/obsidian_rex_sprite_256x192.png',background:'assets/luminous_water_garden_1920.webp'};const V=AwaiRealtimeVFX;let previewMode=stats.focus>stats.power+2?'thunder':'sword';try{const retained=localStorage.getItem(KEY+'.vfx');if(V.styles.includes(retained))previewMode=retained;}catch{}if(V.styles.includes(params.get('fx')))previewMode=params.get('fx');const vfx=V.create(previewMode);let assetsReady=false,assetError=false,director=D.create(state);
  Promise.all(Object.entries(assetUrls).map(([key,url])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{sprites[key]=img;resolve();};img.onerror=reject;img.src=url;}))).then(()=>{assetsReady=true;last=performance.now();render();}).catch(()=>{assetError=true;pause('画像を読み込めません。再読込で試せます。');});
  const motion=matchMedia('(prefers-reduced-motion: reduce)'),canvas=$('rt-canvas');let manual=false,last=0,paint=0,savedAt=0,storageWarning=false;try{manual=localStorage.getItem(KEY+'.motion')==='reduce';}catch{}const reduced=()=>manual||motion.matches;
  function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,signature,battle:state,...(!loaded.restored?{sourceSnapshot:source}:{})}));storageWarning=false;}catch{storageWarning=true;}}
  function pause(reason){if(!state.outcome){state.paused=true;state.pauseReason=reason;}D.flush(director,state);V.clear(vfx);save();render();}
  function reset(){state=R.create(stats,'water-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),state.policy);director=D.create(state);V.clear(vfx);savedAt=0;last=performance.now();save();render();}
  function render(){
    $('rt-vfx-label').textContent='攻撃演出プレビュー · '+({sword:'空間斬り',machinegun:'マシンガン',thunder:'雷'}[vfx.mode]);for(const b of document.querySelectorAll('[data-rt-vfx]'))b.setAttribute('aria-pressed',String(b.dataset.rtVfx===vfx.mode));const shown=director.shown;$('rt-name').textContent=capture?'テスト役':source.name;$('rt-hp').textContent=Math.ceil(shown.hp)+' / '+state.maxHp;$('rt-hp-bar').max=state.maxHp;$('rt-hp-bar').value=shown.hp;$('rt-boss-hp').textContent=Math.ceil(shown.bossHp)+' / '+state.bossMaxHp;$('rt-boss-bar').max=state.bossMaxHp;$('rt-boss-bar').value=shown.bossHp;$('rt-energy').value=state.energy;$('rt-energy-label').textContent=Math.floor(state.energy);
    const action=D.frame(director);$('rt-hit-note').textContent=action&&action.kind!=='impact'?(action.stage==='windup'?(['burst','cleave'].includes(action.kind)?'強い技をためる':action.kind==='cast'?'光を集める':'踏みこむ'):((action.hitCount>1?action.hitIndex+'連撃 · ':'')+Math.round(action.damage*(action.hitIndex/action.hitCount))+'ダメージ')):'';const zone=state.phase.zone;$('rt-signal').textContent=state.outcome?'':zone?({bite:'噛みつき',tail:'尾の薙ぎ払い',charge:'突進'}[state.phase.kind])+'：あと'+state.phase.left.toFixed(1)+'秒':state.opening>0?'体勢が崩れた · 相棒が攻める':state.phase.kind==='recover'?'大牙が体勢を立て直している':'大牙がこちらを見ている';
    $('rt-state').textContent=!assetsReady?(assetError?'画像を再読込してください':'絵を読み込んでいます'):storageWarning?'保存できません':state.outcome==='win'?'勝利':state.outcome==='loss'?'戦闘終了':state.paused?'一時停止中':state.decision;
    for(const b of document.querySelectorAll('[data-rt-policy]')){b.disabled=!!state.outcome;b.setAttribute('aria-pressed',String(state.policy===b.dataset.rtPolicy));}
    $('rt-pause').textContent=state.paused?'▶':'Ⅱ';$('rt-pause').setAttribute('aria-label',state.paused?'再開':'一時停止');$('rt-pause').disabled=!!state.outcome;const visiblePause=state.paused&&(!state.outcome||!director.action);$('rt-overlay').hidden=!visiblePause;$('rt-overlay-title').textContent=state.outcome==='win'?'勝利！':state.outcome==='loss'?'もう一度挑もう':state.pauseReason||'ひと休み';$('rt-result-message').hidden=!state.outcome;$('rt-result-message').textContent=state.outcome==='win'?'水庭に、光が戻った。':state.outcome==='loss'?'ひと息ついて、もう一度。':'';$('rt-resume').hidden=!!state.outcome;$('rt-retry').hidden=!state.outcome;
  }
  function syncMotion(){$('rt-reduced').checked=reduced();$('rt-reduced').disabled=motion.matches;$('rt-motion-note').textContent=motion.matches?'端末の動作軽減設定に合わせています。':'技の光や跳びこみを抑え、移動は判断に必要な位置だけを表示します。';}
  function resume(){if(!assetsReady){if(assetError)location.reload();return;}if(state.outcome||document.hidden)return;state.paused=false;state.pauseReason='';last=performance.now();save();render();}
  $('rt-pause').addEventListener('click',()=>state.paused?resume():pause('ひと休み'));$('rt-resume').addEventListener('click',resume);$('rt-retry').addEventListener('click',reset);
  for(const b of document.querySelectorAll('[data-rt-policy]'))b.addEventListener('click',()=>{if(R.setPolicy(state,b.dataset.rtPolicy)){save();render();}});
  $('rt-menu').addEventListener('click',()=>{pause('一時停止中');$('rt-details').showModal();});$('rt-close').addEventListener('click',()=>$('rt-details').close());$('rt-reduced').addEventListener('change',e=>{manual=e.target.checked;try{localStorage.setItem(KEY+'.motion',manual?'reduce':'full');}catch{}syncMotion();});motion.addEventListener('change',syncMotion);syncMotion();
  for(const b of document.querySelectorAll('[data-rt-vfx]'))b.addEventListener('click',()=>{if(V.setMode(vfx,b.dataset.rtVfx)){try{localStorage.setItem(KEY+'.vfx',vfx.mode);}catch{}render();}});
  $('rt-reset').addEventListener('click',()=>{if(confirm('この戦闘をやり直します。普段の相棒と記録はそのままです。')){$('rt-details').close();reset();}});
  document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)pause('画面を離れていた');});window.addEventListener('pagehide',save);
  function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.round(r.width*d),h=Math.round(r.height*d);if(w<1||h<1)return;if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;}new ResizeObserver(resize).observe($('rt-stage'));resize();
  function tick(now){if(!last)last=now;const dt=Math.min(.08,(now-last)/1000);last=now;if(!document.hidden&&assetsReady){const minimal=reduced(),advance=D.advance(director,dt,{paused:state.paused&&!state.outcome,reduced:minimal});if(advance){R.advance(state,dt);D.capture(director,state,minimal,{style:vfx.mode});}if(now-paint>=16){const visualDt=state.paused&&!state.outcome?0:Math.min(.08,(now-paint)/1000);paint=now;render();AwaiRealtimeWorld.draw(canvas,state,{sprites,reduced:minimal,director,vfx,dt:visualDt,capture});}if(!state.paused&&state.time-savedAt>=.8){savedAt=state.time;save();}if(state.outcome&&savedAt!==-1){save();savedAt=-1;}}requestAnimationFrame(tick);}
  window.AwaiRealtimeScene={current:()=>JSON.parse(JSON.stringify(state)),storageKey:KEY,captureMode:capture,reduced,vfx:()=>V.inspect(vfx),assets:()=>({ready:assetsReady,error:assetError,preview:capture?'開発中・キャラクターは仮表示':'姫系の成長外見プレビュー',urls:assetUrls}),presentation:()=>JSON.parse(JSON.stringify({clock:director.clock,shown:director.shown,action:D.frame(director),contacts:director.contacts})),source:()=>JSON.parse(JSON.stringify({id:source.id,name:capture?'テスト役':source.name,appearance:capture?{kind:'generic-human'}:look,stats,storageKey:E.STORAGE_KEY+suffix,restored:loaded.restored}))};
  save();render();requestAnimationFrame(tick);
})();
