(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./thunder-ritual.js'));else root.AwaiRealtimeVFX=factory(root.AwaiThunderRitual);})(globalThis,function(Ritual){
 'use strict';const LIMIT=64,TAU=Math.PI*2,styles=['sword','machinegun','thunder'],clamp=x=>Math.max(0,Math.min(1,x));
 function create(mode='sword'){return {mode:styles.includes(mode)?mode:'sword',pool:Array.from({length:LIMIT},()=>({active:false})),time:0,lastContact:'',lastFlash:-1,lastOrigin:null,lastTarget:null,metrics:{peak:0,emitted:0,dropped:0,flashes:0,types:{}}};}
 function clear(v){for(const p of v.pool)p.active=false;v.lastContact='';}
 function setMode(v,mode){if(!styles.includes(mode)||v.mode===mode)return false;v.mode=mode;clear(v);return true;}
 function spawn(v,kind,data){const p=v.pool.find(p=>!p.active);if(!p){v.metrics.dropped++;return;}Object.assign(p,{active:true,kind,age:0,life:.5,vx:0,vy:0,gravity:0,rotation:0,spin:0,color:null,...data});v.metrics.emitted++;v.metrics.types[kind]=(v.metrics.types[kind]||0)+1;}
 function update(v,{action,origin,target,scale,dt=0,reduced=false,scene}){dt=Math.max(0,Math.min(.08,dt));v.time+=dt;v.lastOrigin={...origin};v.lastTarget={...target};v.ritual=v.mode==='thunder'&&scene?Ritual.frame(action,scene,reduced):null;
  for(const p of v.pool)if(p.active){p.age+=dt;if(reduced||p.age>=p.life){p.active=false;continue;}if(p.age<0)continue;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=p.gravity*dt;p.rotation+=p.spin*dt;}
  if(!reduced&&action&&action.kind!=='impact'&&action.hitIndex>0){const key=action.id+':'+action.hitIndex;if(key!==v.lastContact){v.lastContact=key;let seed=action.id*97+action.hitIndex*31;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;},strong=action.hitCount===3,dx=target.x-origin.x,dy=target.y-origin.y,len=Math.hypot(dx,dy)||1,ux=dx/len,uy=dy/len;
   if(v.mode==='sword'){spawn(v,'rift',{x:target.x,y:target.y,life:strong?.52:.38,size:scale*(strong?.90:.62),rotation:action.hitIndex%2?-.8:.65});for(let i=0;i<(strong?9:5);i++){const angle=rnd()*TAU;spawn(v,'shard',{x:target.x,y:target.y,vx:Math.cos(angle)*scale*(.25+rnd()*.35),vy:Math.sin(angle)*scale*.3,life:.45+rnd()*.2,rotation:angle,spin:4,size:scale*.025});}}
   else if(v.mode==='machinegun'){for(let i=0;i<(strong?9:6);i++){const delay=i*.022;spawn(v,'bullet',{x:origin.x,y:origin.y+(rnd()-.5)*scale*.055,age:-delay,vx:dx/.14,vy:dy/.14,life:.14,size:scale*.17,rotation:Math.atan2(dy,dx)});}for(let i=0;i<(strong?14:10);i++)spawn(v,'shell',{x:origin.x-ux*scale*.23,y:origin.y-uy*scale*.23,vx:-scale*(.50+rnd()*.80),vy:-scale*(1.40+rnd()*.90),gravity:scale*3,life:.85+rnd()*.25,rotation:rnd()*TAU,spin:(rnd()-.5)*18,size:scale*.055});if(v.time-v.lastFlash>=.34){spawn(v,'muzzle',{x:origin.x,y:origin.y,life:.10,size:scale*.10,rotation:Math.atan2(dy,dx)});v.lastFlash=v.time;v.metrics.flashes++;}for(let i=0;i<6;i++)spawn(v,'spark',{x:target.x,y:target.y,vx:(rnd()-.5)*scale*.6,vy:-rnd()*scale*.6,gravity:scale,life:.34,size:scale*.035});}
   else{v.metrics.types.glyphs=(v.metrics.types.glyphs||0)+1;v.metrics.types.column=(v.metrics.types.column||0)+1;for(let i=0;i<(strong?10:6);i++)spawn(v,'electric',{x:(scene?.ground.x||target.x)+(rnd()-.5)*scale*.50,y:(scene?.ground.y||target.y)-(scene?.bossHeight||scale)*(.12+rnd()*.52),vx:(rnd()-.5)*scale*.5,vy:-scale*(.05+rnd()*.2),gravity:scale*.16,life:.30+rnd()*.22,size:scale*.035,rotation:rnd()*TAU});for(let i=0;i<(strong?7:4);i++)spawn(v,'spark',{x:scene?.ground.x||target.x,y:scene?.ground.y||target.y,vx:(rnd()-.5)*scale*.4,vy:-scale*(.25+rnd()*.4),gravity:scale*.65,life:.36+rnd()*.16,size:scale*.018,color:'#bcf3ff'});}
  }}
  const alive=v.pool.filter(p=>p.active).length;v.metrics.peak=Math.max(v.metrics.peak,alive);
 }
 function origin(v,hand,target,scale,action,reduced=false){const angle=v.mode==='sword'?(!reduced&&action?.kind!=='impact'&&action?.stage==='windup'?-.95:-.25):Math.atan2(target.y-hand.y,target.x-hand.x),x=v.mode==='machinegun'?.355:v.mode==='thunder'?.16:.43,y=v.mode==='thunder'?-.10:0;return {x:hand.x+(Math.cos(angle)*x-Math.sin(angle)*y)*scale,y:hand.y+(Math.sin(angle)*x+Math.cos(angle)*y)*scale};}
 function draw(c,v,{hand,origin,target,scale,action,reduced=false,material=false,heldAsset=false}){
  const outgoing=action&&action.kind!=='impact',contact=outgoing&&action.hitIndex>0,q=action?.contactAge||0,recoil=!reduced&&contact?Math.sin(Math.min(1,q/.18)*Math.PI)*scale*.025:0,angle=Math.atan2(target.y-hand.y,target.x-hand.x);
  // The visible held prop and the particle emitter share the same world-space source.
  if(!heldAsset){c.save();c.translate(hand.x,hand.y);c.rotate(v.mode==='sword'?(!reduced&&outgoing&&action.stage==='windup'?-.95:-.25):angle);
  if(v.mode==='sword'){c.fillStyle='#433c59';c.fillRect(-scale*.06,-scale*.018,scale*.14,scale*.036);c.fillStyle='#d8bc78';c.fillRect(scale*.04,-scale*.055,scale*.025,scale*.11);c.beginPath();c.moveTo(scale*.07,-scale*.025);c.lineTo(scale*.33,-scale*.07);c.lineTo(scale*.49,0);c.lineTo(scale*.33,scale*.07);c.lineTo(scale*.07,scale*.07);c.closePath();c.fillStyle='#232936';c.fill();c.strokeStyle='#9e547a';c.lineWidth=Math.max(1,scale*.01);c.stroke();}
  else if(v.mode==='machinegun'){c.translate(-recoil,0);c.fillStyle='#273f52';c.fillRect(-scale*.06,-scale*.065,scale*.25,scale*.13);c.fillStyle='#6f8393';c.fillRect(scale*.10,-scale*.035,scale*.23,scale*.07);c.fillStyle='#b6c6c8';c.fillRect(scale*.30,-scale*.045,scale*.055,scale*.09);c.fillStyle='#234353';c.fillRect(-scale*.025,scale*.025,scale*.045,scale*.105);c.fillStyle='#b49558';c.fillRect(scale*.045,scale*.05,scale*.05,scale*.09);c.fillStyle='#9dc6ca';c.fillRect(scale*.04,-scale*.083,scale*.06,scale*.025);}
  else{c.strokeStyle='#59618c';c.lineWidth=scale*.018;c.beginPath();c.moveTo(-scale*.05,scale*.16);c.lineTo(scale*.16,-scale*.10);c.stroke();c.beginPath();c.moveTo(scale*.21,-scale*.10);c.lineTo(scale*.16,-scale*.17);c.lineTo(scale*.10,-scale*.10);c.lineTo(scale*.16,-scale*.035);c.closePath();c.fillStyle='#b9e5ff';c.fill();c.strokeStyle='#7471bd';c.lineWidth=scale*.015;c.stroke();}
  c.restore();}
  if(!reduced&&contact&&v.mode==='machinegun'&&q<.22){c.save();c.globalAlpha=(1-q/.22)*.85;c.strokeStyle='#ffe1a2';c.lineWidth=Math.max(2,scale*.013);c.beginPath();c.moveTo(origin.x,origin.y);c.lineTo(target.x,target.y);c.stroke();c.fillStyle='#fff4cc';c.beginPath();c.arc(origin.x,origin.y,scale*.065,0,TAU);c.fill();c.restore();}
  if(material&&v.mode==='thunder')return;if(v.mode==='thunder')Ritual.pillar(c,v.ritual,origin);if(reduced){if(v.mode==='thunder')return;if(contact){c.save();c.globalAlpha=.58;c.lineCap='round';if(v.mode==='sword'){const r=scale*.70;for(const [color,width]of [['#ad554f',scale*.09],['#f4dca3',scale*.035]]){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(target.x-r,target.y+r*.45);c.quadraticCurveTo(target.x,target.y-r*.5,target.x+r,target.y-r*.45);c.stroke();}}else if(v.mode==='machinegun'){c.strokeStyle='#b89b63';c.lineWidth=3;for(let i=0;i<6;i++){const z=i/6,x=origin.x+(target.x-origin.x)*z,y=origin.y+(target.y-origin.y)*z;c.beginPath();c.moveTo(x-6,y);c.lineTo(x+6,y);c.stroke();}}else{for(const [color,width]of [['#648ace',scale*.07],['#d1eaff',2]]){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(origin.x,origin.y);for(let i=1;i<=7;i++){const z=i/7,j=i===7?0:(i%2?1:-1)*scale*.055;c.lineTo(origin.x+(target.x-origin.x)*z,origin.y+(target.y-origin.y)*z+j);}c.stroke();}}c.restore();}return;}
  for(const p of v.pool)if(p.active&&p.age>=0){const t=clamp(p.age/p.life);c.save();c.globalAlpha=(1-t)*.95;c.translate(p.x,p.y);c.rotate(p.rotation);
   if(p.kind==='rift'){const length=p.size,gap=p.size*.065*(1-t);c.lineCap='round';for(const [color,width]of [['#b93f45',length*.22],['#f19a4e',length*.13],['#ffe6a4',length*.075],['#fff9e4',length*.025]]){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(-length,length*.28);c.quadraticCurveTo(0,-length*.35,length,-length*.28);c.stroke();}c.fillStyle='#30204ee0';c.beginPath();c.moveTo(-length,0);c.lineTo(-length*.15,-gap);c.lineTo(length,0);c.lineTo(length*.15,gap);c.closePath();c.fill();for(const [color,width]of [['#927bd4',p.size*.04],['#f2e6ff',p.size*.013]]){c.strokeStyle=color;c.lineWidth=width;c.beginPath();c.moveTo(-length,0);c.lineTo(-length*.15,-gap);c.lineTo(length,0);c.moveTo(-length,0);c.lineTo(length*.15,gap);c.lineTo(length,0);c.stroke();}}
   else if(p.kind==='shell'){c.fillStyle='#9e692c';c.fillRect(-p.size*.28,-p.size*.55,p.size*.56,p.size*1.1);c.strokeStyle='#354455';c.lineWidth=Math.max(1,p.size*.12);c.strokeRect(-p.size*.28,-p.size*.55,p.size*.56,p.size*1.1);c.fillStyle='#ffe09a';c.fillRect(-p.size*.21,-p.size*.48,p.size*.34,p.size*.80);}
   else if(p.kind==='bullet'){c.strokeStyle='#efd5a4';c.lineWidth=Math.max(2,p.size*.13);c.beginPath();c.moveTo(-p.size,0);c.lineTo(0,0);c.stroke();}
   else if(p.kind==='muzzle'){c.fillStyle='#ffc568';c.globalAlpha*=.6;c.beginPath();c.moveTo(0,-p.size*.7);c.lineTo(p.size*1.5,0);c.lineTo(0,p.size*.7);c.lineTo(p.size*.35,0);c.closePath();c.fill();}
   else if(p.kind==='bolt'||p.kind==='branch'||p.kind==='ribbon'){const dx=p.tx-p.x,dy=p.ty-p.y,length=Math.hypot(dx,dy)||1,ux=-dy/length,uy=dx/length;for(const [color,width]of [[p.kind==='ribbon'?'#479bed':p.kind==='bolt'?'#8274dc':'#80acde',p.size],['#e5f6ff',p.size*.28]]){c.strokeStyle=color;c.lineWidth=Math.max(1,width);c.lineJoin='round';c.beginPath();c.moveTo(0,0);for(let i=1;i<=7;i++){const z=i/7,j=i===7?0:Math.sin(p.seed+i*21.7)*scale*(p.kind==='ribbon'?.018:.06);c.lineTo(dx*z+ux*j,dy*z+uy*j);}c.stroke();}}
   else if(p.kind==='sigil'){c.strokeStyle='#96caff';c.lineWidth=Math.max(1,scale*.009);c.beginPath();for(let i=0;i<=6;i++){const angle=i*TAU/6,r=p.size*(1+t*.5);i?c.lineTo(Math.cos(angle)*r,Math.sin(angle)*r):c.moveTo(r,0);}c.stroke();}
   else if(p.kind==='electric'){c.shadowColor='#24a3ff';c.shadowBlur=5;c.strokeStyle='#d8fbff';c.lineWidth=Math.max(1,p.size*.25);c.beginPath();c.moveTo(-p.size,-p.size*.6);c.lineTo(0,0);c.lineTo(-p.size*.3,p.size*.15);c.lineTo(p.size,p.size*.7);c.stroke();}
   else{c.fillStyle=p.color||(p.kind==='spark'?'#ffe6a8':'#c9b4ed');c.fillRect(-p.size*.2,-p.size*.7,p.size*.4,p.size*1.4);}
   c.restore();
  }
 }
 function inspect(v){return {mode:v.mode,limit:LIMIT,alive:v.pool.filter(p=>p.active).length,peak:v.metrics.peak,emitted:v.metrics.emitted,dropped:v.metrics.dropped,flashes:v.metrics.flashes,types:{...v.metrics.types},origin:v.lastOrigin,target:v.lastTarget,ritual:v.ritual?{...v.ritual}:null};}
 function feedback(action,reduced=false){return Ritual.feedback(action,reduced);}
 return {LIMIT,styles,create,clear,setMode,origin,update,draw,inspect,feedback};
});
