(function(root){
  'use strict';const TAU=Math.PI*2,clamp=x=>Math.max(0,Math.min(1,x)),cache=new WeakMap(),tints=new WeakMap(),smooth=x=>x*x*(3-2*x);let lastFrame=null;
  function layout(w,h){const hero=Math.min(w*.42,h*.32),boss=Math.min(w*.72,h*.82),left=hero*.5+10,span=Math.max(1,w-hero-20);return {hero,boss,bossHeight:boss*.75,bossX:w*(w/h<.9?.59:.67),floor:h*.70,left,span,scaleX:span/.74*.75,scaleY:h*.25};}
  function position(p,a,h){return {x:a.left+clamp((p.x-.1)/.74)*a.span*.75,y:a.floor+(p.y-.68)*a.scaleY};}
  function background(canvas,img){let b=cache.get(canvas);if(!b||b.width!==canvas.width||b.height!==canvas.height){b=document.createElement('canvas');b.width=canvas.width;b.height=canvas.height;const c=b.getContext('2d'),k=Math.max(b.width/img.naturalWidth,b.height/img.naturalHeight),w=img.naturalWidth*k,h=img.naturalHeight*k;c.imageSmoothingEnabled=true;c.drawImage(img,(b.width-w)/2,(b.height-h)*.70,w,h);cache.set(canvas,b);}return b;}
  function draw(canvas,s,{sprites,reduced,director,vfx,dt=0,capture=false}){
    if(canvas.width<1||canvas.height<1)return;const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,a=layout(w,h),time=director?.clock||s.time,action=AwaiRealtimeDirector.frame(director),base=position(s.player,a,h),hit={x:a.bossX+a.boss*.01,y:a.floor-a.bossHeight*.48};
    const feedback=AwaiRealtimeVFX.feedback(action,reduced);c.clearRect(0,0,w,h);c.imageSmoothingEnabled=true;c.drawImage(background(canvas,sprites.background),0,0);c.save();c.translate(feedback.shakeX,feedback.shakeY);c.drawImage(background(canvas,sprites.background),0,0);if(!reduced&&action&&['burst','cleave'].includes(action.kind)){c.save();c.globalAlpha=action.stage==='windup'?.20:.11;c.fillStyle='#122234';c.fillRect(0,0,w,h);c.restore();}
    const ring=(x,y,rx,ry,color,line=2)=>{c.beginPath();c.ellipse(x,y,Math.max(.1,rx),Math.max(.1,ry),0,0,TAU);c.strokeStyle=color;c.lineWidth=line;c.stroke();};
    const light=(x,y,r,color)=>{const g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'#d8ffff00');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2);};
    const zone=s.phase.zone;if(zone){const p=position(zone,a,h),rx=zone.rx*a.scaleX,ry=zone.ry*a.scaleY,k=1-s.phase.left/s.phase.full;c.beginPath();c.ellipse(p.x,p.y,rx,ry,0,0,TAU);c.fillStyle='#b05b3c45';c.fill();ring(p.x,p.y,rx,ry,'#9c593a',2);ring(p.x,p.y,rx*k,ry*k,'#ffedba',3);}
    const enemyPose=AwaiEnemyMotion.pose(s,action,reduced);let hx=base.x,hy=base.y,ex=a.bossX+enemyPose.x*a.boss,ey=a.floor+enemyPose.y*a.boss,hr=0,er=enemyPose.rotation,ys=enemyPose.stretch;
    const outgoing=action&&action.kind!=='impact',strong=action&&['burst','cleave'].includes(action.kind),magic=action&&['cast','burst'].includes(action.kind);
    let impulse=0;if(action&&!reduced){const q=action.age;if(outgoing){const tip={x:base.x+a.hero*.35,y:base.y-a.hero*.61},dx=hit.x-tip.x,dy=hit.y-tip.y;if(action.stage==='windup'){const k=clamp(q/action.windup),launch=smooth(clamp((k-.60)/.40));hx-=a.hero*.06*Math.sin(k*Math.PI);hy-=a.hero*.018*Math.sin(k*Math.PI);hr=-.06*Math.sin(k*Math.PI);if(vfx.mode==='sword'){hx+=dx*launch;hy+=dy*launch-Math.sin(launch*Math.PI)*a.hero*.1;}}else if(vfx.mode==='sword'){const k=1-smooth(clamp((q-action.windup-.13)/.35));hx+=dx*k;hy+=dy*k;hr=.055*k;}if(action.stage!=='windup'){const k=clamp(action.contactAge/.40);impulse=Math.sin(Math.min(1,k*2)*Math.PI);const room=Math.max(0,w-a.bossX-a.boss*.5-5);ex+=Math.min(room,a.hero*(strong?.20:.13))*impulse;er=(strong?.09:.06)*impulse;ys=1-(strong?.065:.045)*impulse;}}else{const k=clamp(q/.48);impulse=Math.sin(k*Math.PI);if(!action.blocked){hx-=a.hero*.055*impulse;hr=-.08*impulse;}}}
    if(outgoing&&!reduced&&vfx.mode!=='sword'){const k=action.stage==='windup'?smooth(clamp(action.elapsed/action.windup)):1-smooth(clamp((action.contactAge-.32)/.24));hx-=Math.min(a.hero*.40,Math.max(0,base.x-a.hero*.5-10))*k;hr-=.035*k;}if(!reduced){hy+=Math.sin(time*2.2)*a.hero*.008;ys+=Math.sin(time*1.7)*.004;if(zone)er+=(s.phase.kind==='bite'?-.028:.024)*Math.sin((1-s.phase.left/s.phase.full)*Math.PI);}
    if(outgoing&&vfx.mode==='thunder'){const k=reduced?1:smooth(clamp(action.elapsed/Math.max(.01,action.windup*.23)));hx-=Math.max(0,hx-a.left)*k;}
    function shadow(x,y,size){c.fillStyle='#17393b36';c.beginPath();c.ellipse(x,y+3,size*.26,size*.045,0,0,TAU);c.fill();}shadow(ex,ey,a.boss);shadow(base.x,base.y+8,a.hero);
    const heroRight=hx+a.hero*((capture?.43:.5)+Math.abs(hr)),ritualScene={ground:{x:a.bossX,y:a.floor},width:w,height:h,boss:a.boss,bossHeight:a.bossHeight,hero:a.hero,heroRight};const materialFrames=AwaiRealtimeDirector.materialFrames(director).map(m=>AwaiMagicMaterial.frame(m,reduced)).filter(Boolean),materialFrame=materialFrames.at(-1)||null,materialSize=Math.min(a.boss*1.12,w*.90);if(sprites.magicBack&&sprites.magicFront&&materialFrame)for(const frame of materialFrames)AwaiMagicMaterial.draw(c,sprites.magicBack,frame,ritualScene.ground,materialSize);if(vfx.mode==='thunder'&&action?.material!==true)AwaiThunderRitual.ground(c,AwaiThunderRitual.frame(action,ritualScene,reduced));
    function actor(img,x,y,width,height,rotation=0,stretch=1,flash=0,jaw=0){c.save();c.translate(x,y);c.rotate(rotation);c.scale(1,stretch);c.imageSmoothingEnabled=false;if(jaw>0&&s.enemy!=='robot'){const crop={x:12,y:79,w:57,h:26},sx=width/img.naturalWidth,sy=height/img.naturalHeight;const left=-width*.5,top=-height*.922;c.save();c.beginPath();c.rect(left,top,width,height);c.rect(left+(crop.x+crop.w)*sx,top+crop.y*sy,-crop.w*sx,crop.h*sy);c.clip('evenodd');c.drawImage(img,left,top,width,height);c.restore();c.save();c.translate(left+(crop.x+crop.w)*sx,top+crop.y*sy);c.rotate(-jaw*.30);c.drawImage(img,crop.x,crop.y,crop.w,crop.h,-crop.w*sx,0,crop.w*sx,crop.h*sy);c.restore();}else c.drawImage(img,-width*.5,-height*.922,width,height);if(flash>0){const tintColor=vfx.mode==='thunder'?'#d7f8ff':'#ffffff';let palette=tints.get(img);if(!palette){palette={};tints.set(img,palette);}let tinted=palette[tintColor];if(!tinted){tinted=document.createElement('canvas');tinted.width=img.naturalWidth;tinted.height=img.naturalHeight;const t=tinted.getContext('2d');t.drawImage(img,0,0);t.globalCompositeOperation='source-atop';t.fillStyle=tintColor;t.fillRect(0,0,tinted.width,tinted.height);palette[tintColor]=tinted;}c.save();if(vfx.mode!=='thunder'){c.beginPath();c.ellipse(0,-height*.48,width*.23,height*.20,0,0,TAU);c.clip();}c.globalAlpha=vfx.mode==='thunder'?flash*.70:flash;c.drawImage(tinted,-width*.5,-height*.922,width,height);c.restore();}c.restore();}
    function robotActor(x,y,size,rotation,flash){const rig={"anchor":{"x":256,"y":430},"frameSize":512,"pixelGrid":128,"paletteColors":96,"frontPivot":[141,182],"backPivot":[381,190],"core":[207,152],"sourceHash":"431b6c259766a65febb231aa565daa86fd66aa47de7e7f7747ce2b772f3f6a13"};c.save();c.translate(x,y);c.rotate(rotation);const k=size/512;function layer(img,pivot,angle=0){c.save();if(pivot){c.translate((pivot[0]-256)*k,(pivot[1]-430)*k);c.rotate(angle);c.drawImage(img,-pivot[0]*k,-pivot[1]*k,size,size);}else c.drawImage(img,-256*k,-430*k,size,size);c.restore();}layer(sprites.robotBack,rig.backPivot,-(enemyPose.arm||0)*.45);layer(sprites.enemy);layer(sprites.robotFront,rig.frontPivot,enemyPose.arm||0);if(enemyPose.core>0){const cx=(rig.core[0]-256)*k,cy=(rig.core[1]-430)*k;light(cx,cy,size*.19*enemyPose.core,'#70e9ffb0');if(!reduced){ring(cx,cy,size*(.10+enemyPose.core*.22),size*(.10+enemyPose.core*.22),'#acf7ff',2);}}if(flash>0){c.globalAlpha=flash*.22;layer(sprites.enemy);}c.restore();}
    const victorious=s.outcome==='win'&&director.shown.bossHp<=0,finish=victorious&&!reduced?(action?smooth(clamp(action.contactAge/.5)):1):0;c.save();c.globalAlpha=1;if(s.enemy==='robot')robotActor(ex,ey+finish*a.boss*.045,a.boss,er+finish*.055,feedback.flash);else actor(sprites.enemy,ex,ey+finish*a.boss*.045,a.boss,a.bossHeight,er+finish*.055,ys,feedback.flash,enemyPose.jaw);c.restore();if(sprites.warriorLook&&AwaiWarriorMaterial.inspect().ready){let figure=cache.get(sprites.player);if(!figure){figure=document.createElement('canvas');figure.width=figure.height=512;cache.set(sprites.player,figure);}AwaiCreature.draw(figure,{...sprites.warriorLook,weapon:vfx.mode},time*1000,reduced,{armAngle:outgoing&&!reduced?(action.stage==='windup'?-.04*smooth(clamp(action.age/action.windup)):.07*impulse):0});actor(figure,hx,hy-(victorious&&!reduced?a.hero*.025:0),a.hero,a.hero,hr);}else actor(sprites.player,hx,hy-(victorious&&!reduced?a.hero*.025:0),a.hero,a.hero,hr);lastFrame={enemy: s.enemy,material:materialFrame,materials:materialFrames,materialGround:ritualScene.ground,enemyPose,enemyAlpha:1,heroRight,ground:{x:a.bossX,y:a.floor},enemyFootRadius:a.boss*.22,actionId:action?.id,hitIndex:action?.hitIndex,stage:action?.stage,...feedback};
    const focus={x:hx+a.hero*.35,y:hy-a.hero*.61},hand={x:hx+a.hero*(capture?.24:.36),y:hy-a.hero*(capture?.43:.105)},emitter=AwaiRealtimeVFX.origin(vfx,hand,hit,a.hero,action,reduced);AwaiRealtimeVFX.update(vfx,{action,origin:emitter,target:hit,scale:a.hero,dt,reduced,scene:ritualScene});AwaiRealtimeVFX.draw(c,vfx,{hand,origin:emitter,target:hit,scale:a.hero,action,reduced,material:action?.material===true,heldAsset:!!sprites.warriorLook});if(sprites.magicBack&&sprites.magicFront&&materialFrame)for(const frame of materialFrames)AwaiMagicMaterial.draw(c,sprites.magicFront,frame,ritualScene.ground,materialSize);if(s.shield>0){ring(hx,hy-a.hero*.48,a.hero*.43,a.hero*.5,'#bcecec',2);ring(hx,hy-a.hero*.48,a.hero*.45,a.hero*.52,'#387d92',1);}
    if(action){const p=outgoing?hit:{x:hx,y:hy-a.hero*.48},q=action.age,post=action.contactAge;
      if(action.stage==='windup'){const k=clamp(q/action.windup);if(outgoing){}else if(magic){light(focus.x,focus.y,a.hero*.18*k,'#aeeaff8c');ring(focus.x,focus.y,a.hero*(.035+.045*k),a.hero*(.035+.045*k),'#e4eaff',2);const z=clamp((k-.4)/.6),x=focus.x+(hit.x-focus.x)*z,y=focus.y+(hit.y-focus.y)*z-Math.sin(z*Math.PI)*a.hero*.18;light(x,y,a.hero*(strong?.17:.09),'#d5e5ffb0');}else{c.strokeStyle='#f4d397aa';c.lineWidth=3;c.beginPath();c.moveTo(focus.x-12,focus.y+10);c.lineTo(focus.x+10,focus.y-12);c.stroke();}}
      else{const k=clamp(post/.48);if(reduced){if(!outgoing)ring(p.x,p.y,12,12,'#d6d7aa',2);}else{c.save();c.globalAlpha=1-k;if(outgoing){}else{ring(hx,hy-a.hero*.48,a.hero*.46,a.hero*.50,action.blocked?'#dcffff':'#e4c89f',3);}
        const ground=outgoing?{x:a.bossX,y:a.floor}:position(action,a,h);if(!(outgoing&&vfx.mode==='thunder'))ring(ground.x,ground.y,a.hero*(.18+k*.65),a.hero*(.04+k*.14),action.blocked?'#aee6e5':'#e7d3ac',3);c.restore();}
        const damage=action.miss?'回避':String(Math.round(action.damage*(action.hitIndex/action.hitCount))||'');if(damage){const bounce=reduced?0:Math.sin(Math.min(1,post/.32)*Math.PI)*a.hero*.10,numberY=p.y-20-bounce-(reduced?0:Math.max(0,post-.32)*a.hero*.14),size=Math.max(strong?37:29,w*(strong?.080:.064));c.save();c.globalAlpha=reduced?1:Math.min(1,(1-clamp(post/.62))*2);c.textAlign='center';c.lineJoin='round';c.font='900 '+size+'px system-ui';c.strokeStyle='#182137';c.lineWidth=strong?7:6;c.strokeText(damage,p.x,numberY);c.fillStyle=strong?'#ffd16c':'#ffffff';c.fillText(damage,p.x,numberY);const note=action.hitCount>1?action.hitIndex+'連撃':action.interrupted?'大技を中断':action.blocked?'防御':'';if(note){c.font='800 '+Math.max(13,size*.39)+'px system-ui';c.lineWidth=4;c.strokeText(note,p.x,numberY+size*.51);c.fillText(note,p.x,numberY+size*.51);}c.restore();}lastFrame.damageLabel=damage;lastFrame.damageStrong=!!strong;}
    }
    c.restore();if(capture){c.save();const size=Math.max(12,w*.015);c.font='700 '+size+'px system-ui';c.textAlign='center';c.fillStyle='#203e55b0';c.fillRect(0,h-size*2,w,size*2);c.fillStyle='#f3ffff';c.fillText('開発中・キャラクターは仮表示',w*.5,h-size*.6);c.restore();}
  }
  root.AwaiRealtimeWorld={layout,position,draw,inspect:()=>lastFrame?JSON.parse(JSON.stringify(lastFrame)):null};
})(globalThis);
