(function(){
  'use strict';const E=AwaiEngine,C=AwaiCombat,R=AwaiRealtime,$=id=>document.getElementById(id),params=new URLSearchParams(location.search),capture=document.body.dataset.capture==='1',trial=params.get('trial')==='1',slot=trial&&/^[a-z0-9-]{8,48}$/.test(params.get('slot')||'')?params.get('slot'):null,suffix=trial?(slot?'.trial.'+slot:'.trial'):'',development=document.body.dataset.development==='1',enemy=params.get('enemy')==='robot'?'robot':'rex',KEY='awai.scene.realtime.v1'+suffix+(capture?'.capture':development?'.development':'')+(enemy==='robot'?'.robot':''),SCOPE=E.STORAGE_KEY+suffix;
  const loaded=E.load({getItem:k=>localStorage.getItem(k+suffix)});let saved,source=loaded.state;try{saved=JSON.parse(localStorage.getItem(KEY));if(!loaded.restored&&saved?.sourceSnapshot&&typeof saved.sourceSnapshot.id==='string')source=E.hydrate(saved.sourceSnapshot);}catch{}C.ensure(source);let stats=C.effective(source.gameplay),look={...source.appearance,parts:[...source.gameplay.equipped],locomotion:source.gameplay.locomotion},signature=source.id+JSON.stringify(stats)+JSON.stringify(look.parts);const pendingWon=saved?.battle?.bossHp===0&&saved?.battle?.rewardTicket?.sourceId===source.id&&saved?.battle?.rewardTicket?.scope===SCOPE&&saved?.battle?.rewardTicket?.battleId===saved?.battle?.id;const pendingPrepared=saved?.battle?.rewardPreparation?.sourceId===source.id&&saved?.battle?.rewardPreparation?.scope===SCOPE&&saved?.battle?.rewardPreparation?.battleId===saved?.battle?.id;let state=saved?.signature===signature||pendingWon||pendingPrepared?R.hydrate(saved.battle):null;const restoredBattle=!!state;const rewardMode=!capture&&document.body.dataset.development!=='1';if(!state){state=R.create(stats,'water-'+Date.now()+'-'+Math.random().toString(36).slice(2,10),undefined,enemy);state.rewardEligible=rewardMode&&loaded.restored&&!source.gameplay.battle;}let legacyPolicy=restoredBattle&&(saved?.legacyPolicy===true||saved?.lookWeapon===undefined);let meleeWeapon=saved?.lookWeapon===look.weapon&&saved?.meleeWeapon==='machinegun'?'machinegun':look.weapon==='machinegun'?'machinegun':'sword';let nextPolicy=restoredBattle&&['magic','melee'].includes(saved?.nextPolicy)?saved.nextPolicy:state.policy;const explicitWeapon=source.baseStyle.weaponChosen===true,weaponChanged=saved?.lookWeapon===undefined?explicitWeapon:saved.lookWeapon!==look.weapon||(explicitWeapon&&((saved.weaponRevision||0)!==(source.baseStyle.weaponRevision||0)||saved.weaponChosen!==true));if((!restoredBattle||weaponChanged)&&look.weapon){nextPolicy=look.weapon==='thunder'?'magic':'melee';if(!legacyPolicy)R.setPolicy(state,nextPolicy);}
  for(const [id,value] of [['rt-rex','rex'],['rt-robot','robot']])if($(id)){const link=new URL('realtime.html',location.href);if(trial){link.searchParams.set('trial','1');if(slot)link.searchParams.set('slot',slot);}if(value==='robot')link.searchParams.set('enemy','robot');$(id).href=link.href;if(enemy===value)$(id).setAttribute('aria-current','page');}const back=new URL('index.html',location.href);if(trial){back.searchParams.set('trial','1');if(slot)back.searchParams.set('slot',slot);}if(!capture)$('rt-back').href=back.href;if($('rt-training'))$('rt-training').href=back.href;if($('rt-custom')){const customBack=new URL(back);customBack.searchParams.set('view','custom');$('rt-custom').href=customBack.href;}
  if(!loaded.restored&&!capture)$('rt-source-note').textContent='育成の保存がないため、この一戦だけの相棒です。相棒と戦闘をこの端末に保存し、元の育成枠は変更しません。経験・報酬は増えません。画面を離れると一時停止します。';
  const avatar=document.createElement('canvas');avatar.width=400;avatar.height=400;if(!capture)AwaiCreature.draw(avatar,{...look,weapon:'none'},0,true);const D=AwaiRealtimeDirector,sprites={},assetUrls={player:capture?AwaiCaptureActor.imageUrl():avatar.toDataURL('image/png'),enemy:enemy==='robot'?'assets/material/robot-body.png':'assets/obsidian_rex_sprite_256x192.png',background:'assets/luminous_water_garden_1920.webp',...(enemy==='robot'?{robotFront:'assets/material/robot-arm-front.png',robotBack:'assets/material/robot-arm-back.png'}:{})};const warriorMaterial=!!(window.AwaiWarriorMaterial?.uses(look));if(warriorMaterial)sprites.warriorLook=look;const V=AwaiRealtimeVFX;const modeForPolicy=()=>(state.outcome?nextPolicy:state.policy)==='magic'?'thunder':meleeWeapon;let previewMode=modeForPolicy();const vfx=V.create(previewMode);let rewardResult=null,rewardBusy=false,ticketBusy=false,ticketAttemptAt=0;let assetsReady=false,baseReady=false,magicReady=false,baseError=false,magicError=false,magicPromise=null,assetError=false,director=D.create(state);
  function readiness(){const needsMagic=modeForPolicy()==='thunder';assetError=baseError||(needsMagic&&magicError);assetsReady=baseReady&&!baseError&&(!needsMagic||(magicReady&&!magicError));return assetsReady;}
  function loadMagic(){if(magicReady)return Promise.resolve();if(magicPromise)return magicPromise;magicError=false;readiness();Object.assign(assetUrls,{magicBack:'assets/material/lightning-back-48.png',magicFront:'assets/material/lightning-front-48.png'});magicPromise=Promise.all(['magicBack','magicFront'].map(key=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve([key,img]);img.onerror=()=>reject(Error('magic-asset-load-failed'));img.src=assetUrls[key];}))).then(pair=>{Object.assign(sprites,Object.fromEntries(pair));magicReady=true;magicError=false;readiness();last=performance.now();render();}).catch(error=>{magicError=true;magicReady=false;readiness();if(modeForPolicy()==='thunder'){state.paused=true;state.pauseReason='魔法の画像を読み込めません。再開で再試行できます。';save();}render();throw error;}).finally(()=>{magicPromise=null;});return magicPromise;}
  Promise.all([...(warriorMaterial?[AwaiWarriorMaterial.load()]:[]),...Object.entries(assetUrls).map(([key,url])=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{sprites[key]=img;resolve();};img.onerror=reject;img.src=url;}))]).then(()=>{baseReady=true;readiness();if(modeForPolicy()==='thunder')loadMagic().catch(()=>{});last=performance.now();render();}).catch(()=>{baseError=true;readiness();pause('画像を読み込めません。再読込で試せます。');});
  const motion=matchMedia('(prefers-reduced-motion: reduce)'),canvas=$('rt-canvas');let manual=false,last=0,paint=0,savedAt=0,storageWarning=false;try{manual=localStorage.getItem(KEY+'.motion')==='reduce';}catch{}const reduced=()=>manual||motion.matches;
  function save(){try{localStorage.setItem(KEY,JSON.stringify({version:1,signature,battle:state,lookWeapon:look.weapon,meleeWeapon,nextPolicy,legacyPolicy,weaponChosen:explicitWeapon,weaponRevision:source.baseStyle.weaponRevision||0,...(!loaded.restored?{sourceSnapshot:source}:{})}));storageWarning=false;return true;}catch{storageWarning=true;return false;}}
  function pause(reason){if(!state.outcome){state.paused=true;state.pauseReason=reason;}D.flush(director,state);V.clear(vfx);save();render();}
  function reset(){if(nextPolicy==='magic')loadMagic().catch(()=>{});if(unsettled()||state.rewardPreparation||ticketBusy)return;if(rewardMode){const latest=E.load({getItem:k=>localStorage.getItem(k+suffix)});if(latest.restored&&latest.state.id===source.id){C.ensure(latest.state);source=latest.state;stats=C.effective(source.gameplay);signature=source.id+JSON.stringify(stats)+JSON.stringify(look.parts);}}state=R.create(stats,'water-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),nextPolicy,enemy);state.rewardEligible=rewardMode&&loaded.restored&&!source.gameplay.battle;legacyPolicy=false;rewardResult=null;director=D.create(state);readiness();V.setMode(vfx,modeForPolicy());V.clear(vfx);savedAt=0;last=performance.now();save();render();mintTicket();}
  const rewardStorage={getItem:k=>localStorage.getItem(k+suffix),setItem:(k,v)=>localStorage.setItem(k+suffix,v)};
  function rewardLock(work){return AwaiSaveGuard.lock(SCOPE,work);}
  function unsettled(){return !!(state.outcome==='win'&&state.rewardEligible&&(!rewardResult||!rewardResult.ok));}
  function completeTicket(battle){const prep=battle.rewardPreparation;if(!prep||!battle.rewardTicket)return false;battle.rewardPreparation=null;battle.paused=prep.returnPaused;battle.pauseReason=prep.returnPaused?'ひと休み':'';if(save()){rewardResult=null;return true;}battle.rewardPreparation=prep;prep.status='failed';prep.error='battle-save-failed';battle.paused=true;battle.pauseReason='報酬の保存準備ができません。空き容量を確認して再試行してください。';return false;}
  function mintTicket(){if(ticketBusy||!rewardMode||!state.rewardEligible||state.rewardTicket)return;ticketAttemptAt=performance.now();const battle=state;const prep=battle.rewardPreparation||{version:1,sourceId:source.id,scope:SCOPE,battleId:battle.id,status:'pending',error:'',returnPaused:battle.paused};battle.rewardPreparation=prep;prep.status='pending';ticketBusy=true;battle.paused=true;save();rewardLock(async()=>{const latest=await AwaiSaveGuard.latest(rewardStorage,SCOPE);if(!latest.restored||latest.state.id!==source.id)throw Error('target-mismatch');return AwaiAutoRewards.issue(rewardStorage,source.id,SCOPE,battle.id);}).then(ticket=>{if(state!==battle)return;battle.rewardTicket=ticket;completeTicket(battle);}).catch(error=>{if(state!==battle)return;if(error.message==='target-mismatch'){battle.rewardEligible=false;battle.rewardPreparation=null;battle.paused=true;battle.pauseReason='相棒が変わりました。育成へ戻ってください。';}else{prep.status='failed';prep.error=error.message;battle.paused=true;battle.pauseReason='報酬の保存準備ができません。空き容量とブラウザの対応を確認してください。';}rewardResult={ok:false,reason:'ticket-unavailable'};save();}).finally(()=>{if(state===battle){ticketBusy=false;last=performance.now();render();}});}
  function claimReward(){if(rewardBusy||!rewardMode||state.outcome!=='win'||!state.rewardEligible||director.action||rewardResult?.ok)return;rewardBusy=true;const battle=state;AwaiAutoRewards.settle(rewardStorage,battle,SCOPE).then(result=>{if(state!==battle)return;rewardResult=result;if(result.reason==='already-claimed'){const latest=E.load(rewardStorage).state;C.ensure(latest);rewardResult={ok:true,parts:[],...(latest.gameplay.autoProgress.last?.id===battle.id?latest.gameplay.autoProgress.last:{})};}if(rewardResult.ok){const latest=E.load(rewardStorage).state;if(latest.id!==battle.rewardTicket.sourceId){rewardResult={ok:false,reason:'target-mismatch'};return;}source=latest;C.ensure(source);stats=C.effective(source.gameplay);signature=source.id+JSON.stringify(stats)+JSON.stringify(look.parts);}save();render();}).catch(()=>{rewardResult={ok:false,reason:'save-failed'};render();}).finally(()=>{rewardBusy=false;});}
  function render(){
    $('rt-vfx-label').textContent='攻撃演出プレビュー · '+({sword:'空間斬り',machinegun:'マシンガン',thunder:'雷'}[vfx.mode]);for(const b of document.querySelectorAll('[data-rt-vfx]'))b.setAttribute('aria-pressed',String(b.dataset.rtVfx===vfx.mode));$('rt-retry').disabled=unsettled()||ticketBusy||!!state.rewardPreparation;$('rt-reset').disabled=unsettled()||ticketBusy||!!state.rewardPreparation;if($('rt-enemy-name'))$('rt-enemy-name').textContent=state.enemy==='robot'?'水庭の巨機':'水庭の大牙';const shown=director.shown;$('rt-name').textContent=capture?'テスト役':source.name;$('rt-hp').textContent=Math.ceil(shown.hp)+' / '+state.maxHp;$('rt-hp-bar').max=state.maxHp;$('rt-hp-bar').value=shown.hp;$('rt-boss-hp').textContent=Math.ceil(shown.bossHp)+' / '+state.bossMaxHp;$('rt-boss-bar').max=state.bossMaxHp;$('rt-boss-bar').value=shown.bossHp;$('rt-energy').value=state.energy;$('rt-energy-label').textContent=Math.floor(state.energy);
    const action=D.frame(director);$('rt-hit-note').textContent=action&&action.kind!=='impact'?(action.stage==='windup'?(['burst','cleave'].includes(action.kind)?'強い技をためる':action.kind==='cast'?'光を集める':'踏みこむ'):((action.hitCount>1?action.hitIndex+'連撃 · ':'')+Math.round(action.damage*(action.hitIndex/action.hitCount))+'ダメージ')):'';const zone=state.phase.zone;$('rt-signal').textContent=state.outcome?'':zone?(state.enemy==='robot'?{bite:'鉄拳',tail:'コア放電',charge:'突進パンチ'}:{bite:'噛みつき',tail:'尾の薙ぎ払い',charge:'突進'})[state.phase.kind]+'：あと'+state.phase.left.toFixed(1)+'秒':state.opening>0?'体勢が崩れた · 相棒が攻める':state.phase.kind==='recover'?'相手が体勢を立て直している':'相手がこちらを見ている';
    $('rt-state').textContent=!assetsReady?(assetError?'画像を再読込してください':'絵を読み込んでいます'):storageWarning?'保存できません':state.outcome==='win'?'勝利':state.outcome==='loss'?'戦闘終了':state.paused?'一時停止中':state.decision;
    for(const b of document.querySelectorAll('[data-rt-policy]')){b.disabled=!!state.outcome;b.setAttribute('aria-pressed',String(state.policy===b.dataset.rtPolicy));}
    $('rt-pause').textContent=state.paused?'▶':'Ⅱ';$('rt-pause').setAttribute('aria-label',state.paused?'再開':'一時停止');$('rt-pause').disabled=!!state.outcome;const visiblePause=state.paused&&!state.outcome;$('rt-overlay').hidden=!visiblePause;$('rt-overlay-title').textContent=state.outcome==='win'?'勝利！':state.outcome==='loss'?'もう一度挑もう':state.pauseReason||'ひと休み';$('rt-result-message').hidden=!state.outcome;$('rt-result-message').textContent=state.outcome==='win'?'水庭に、光が戻った。':state.outcome==='loss'?'ひと息ついて、もう一度。':'';$('rt-resume').hidden=!!state.outcome;$('rt-resume').textContent=state.rewardPreparation?'保存準備を再試行':'再開';if($('rt-result')){$('rt-result').hidden=!state.outcome||!!director.action;$('rt-result-title').textContent=state.outcome==='win'?'勝利！':'戦闘終了';$('rt-result-line').textContent=state.outcome==='win'?(rewardResult?.ok?'経験 +1 · '+(rewardResult.parts.length?rewardResult.parts.map(id=>C.PARTS[id].name).join(' / ')+'を獲得':'戦いの経験を重ねた'):state.rewardEligible?(rewardResult?.reason==='save-failed'?'保存できません。空き容量を確認して再読込してください。':rewardResult?.reason==='legacy-battle'?'保存中の旧戦闘を終えると、この戦闘の報酬を記録できます。':rewardResult?.reason==='target-mismatch'?'相棒または保存枠が変わったため、この勝利の報酬は付与しません。育成へ戻ってください。':'報酬を保存中…'):'水庭に、光が戻った。'):'ひと息ついて、能力や装備を整えよう。';}for(const b of document.querySelectorAll('[data-rt-weapon]')){b.disabled=!!state.outcome;b.setAttribute('aria-pressed',String(meleeWeapon===b.dataset.rtWeapon&&state.policy==='melee'));}
  }
  function syncMotion(){$('rt-reduced').checked=reduced();$('rt-reduced').disabled=motion.matches;$('rt-motion-note').textContent=motion.matches?'端末の動作軽減設定に合わせています。':'技の光や跳びこみを抑え、移動は判断に必要な位置だけを表示します。';}
  function resume(){if(ticketBusy)return;if(state.rewardPreparation){if(state.rewardTicket)completeTicket(state);else mintTicket();render();return;}if(state.rewardEligible&&!state.rewardTicket){mintTicket();return;}readiness();if(!assetsReady){if(baseError)location.reload();else if(modeForPolicy()==='thunder')loadMagic().catch(()=>{});render();return;}if(state.outcome||document.hidden)return;state.paused=false;state.pauseReason='';last=performance.now();save();render();}
  $('rt-pause').addEventListener('click',()=>state.paused?resume():pause('ひと休み'));$('rt-resume').addEventListener('click',resume);$('rt-retry').addEventListener('click',reset);
  for(const b of document.querySelectorAll('[data-rt-policy]'))b.addEventListener('click',()=>{if(state.outcome)return;R.setPolicy(state,b.dataset.rtPolicy);nextPolicy=state.policy;readiness();if(state.policy==='magic')loadMagic().catch(()=>{});if(!director.action)V.setMode(vfx,modeForPolicy());save();render();});
  for(const b of document.querySelectorAll('[data-rt-weapon]'))b.addEventListener('click',()=>{if(state.outcome)return;meleeWeapon=b.dataset.rtWeapon;R.setPolicy(state,'melee');nextPolicy=state.policy;readiness();if(!director.action)V.setMode(vfx,modeForPolicy());save();render();});
  $('rt-menu').addEventListener('click',()=>{pause('一時停止中');$('rt-details').showModal();});$('rt-close').addEventListener('click',()=>$('rt-details').close());$('rt-reduced').addEventListener('change',e=>{manual=e.target.checked;try{localStorage.setItem(KEY+'.motion',manual?'reduce':'full');}catch{}syncMotion();});motion.addEventListener('change',syncMotion);syncMotion();
  for(const b of document.querySelectorAll('[data-rt-vfx]'))b.addEventListener('click',()=>{if(V.setMode(vfx,b.dataset.rtVfx)){if(b.dataset.rtVfx==='thunder')loadMagic().catch(()=>{});try{localStorage.setItem(KEY+'.vfx',vfx.mode);}catch{}render();}});
  $('rt-reset').addEventListener('click',()=>{if(confirm('この戦闘をやり直します。普段の相棒と記録はそのままです。')){$('rt-details').close();reset();}});
  document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)pause('画面を離れていた');});window.addEventListener('pagehide',save);
  function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1),w=Math.round(r.width*d),h=Math.round(r.height*d);if(w<1||h<1)return;if(canvas.width!==w)canvas.width=w;if(canvas.height!==h)canvas.height=h;}new ResizeObserver(resize).observe($('rt-stage'));resize();
  function tick(now){if(!last)last=now;const dt=Math.min(.08,(now-last)/1000);last=now;if(state.rewardPreparation&&state.rewardTicket&&!ticketBusy&&now-ticketAttemptAt>=1000){ticketAttemptAt=now;completeTicket(state);render();}if(state.rewardEligible&&!state.rewardTicket&&!ticketBusy&&now-ticketAttemptAt>=1000)mintTicket();if(!document.hidden&&assetsReady){const minimal=reduced(),advance=D.advance(director,dt,{paused:state.paused&&!state.outcome,reduced:minimal});if(advance){if(!director.action)V.setMode(vfx,modeForPolicy());R.advance(state,dt);if(state.effects.some(e=>e.id>director.seen&&['strike','cast','burst','cleave'].includes(e.kind)))V.setMode(vfx,modeForPolicy());D.capture(director,state,minimal,{style:vfx.mode,material:magicReady&&!!sprites.magicBack&&!!sprites.magicFront});}if(now-paint>=16){const visualDt=state.paused&&!state.outcome?0:Math.min(.08,(now-paint)/1000);paint=now;render();AwaiRealtimeWorld.draw(canvas,state,{sprites,reduced:minimal,director,vfx,dt:visualDt,capture});}if(!state.paused&&state.time-savedAt>=.8){savedAt=state.time;save();}if(state.outcome&&!director.action){claimReward();if(savedAt!==-1){save();savedAt=-1;}}}requestAnimationFrame(tick);}
  window.AwaiRealtimeScene={current:()=>JSON.parse(JSON.stringify(state)),nextPolicy:()=>nextPolicy,storageKey:KEY,captureMode:capture,reduced,vfx:()=>V.inspect(vfx),assets:()=>({ready:assetsReady,error:assetError,baseReady,magicReady,baseError,magicError,magicLoading:!!magicPromise,registeredMagic:!!sprites.magicBack&&!!sprites.magicFront,preview:capture?'開発中・キャラクターは仮表示':'保存した相棒の色・顔・浮遊パーツ',material:{frames:48,fps:24,authoringAnchor:{x:256,y:430},runtimeFrame:256,runtimeAnchor:{x:128,y:215},decodedAtlasMiB:24,robotPixelGrid:128},urls:assetUrls}),presentation:()=>JSON.parse(JSON.stringify({clock:director.clock,shown:director.shown,action:D.frame(director),materials:D.materialFrames(director),contacts:director.contacts})),source:()=>JSON.parse(JSON.stringify({id:source.id,name:capture?'テスト役':source.name,appearance:capture?{kind:'generic-human'}:look,stats,storageKey:E.STORAGE_KEY+suffix,restored:loaded.restored}))};
  save();render();mintTicket();requestAnimationFrame(tick);
})();
